IMPORTANDO

In [4]:
import pandas as pd
import json
%load_ext autoreload
%autoreload 2
import utils
import warnings
warnings.filterwarnings("ignore")
import ast

In [4]:
path = 'australian_users_items.json'

rows2 = []

with open (path, encoding='utf-8') as f:
    for line in f.readlines():
        rows2.append(ast.literal_eval(line))

df_items = pd.DataFrame(rows2)

unpacked_data = []
for index, row in df_items.iterrows():
    user_id = row['user_id']
    items_count = row['items_count']
    steam_id = row['steam_id']
    user_url = row['user_url']
    for review_dict in row['items']:
        review_dict['user_id'] = user_id
        review_dict['items_count'] = items_count
        review_dict['steam_id'] = steam_id
        review_dict['user_url'] = user_url
        unpacked_data.append(review_dict)

df_items = pd.DataFrame(unpacked_data)

In [5]:
df_items

,item_id,item_name,playtime_forever,playtime_2weeks,user_id,items_count,steam_id,user_url
0,10,Counter-Strike,6,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,20,Team Fortress Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,30,Day of Defeat,7,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,40,Deathmatch Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
4,50,Half-Life: Opposing Force,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
...,...,...,...,...,...,...,...,...
5153204,346330,BrainBread 2,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153205,373330,All Is Dust,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153206,388490,One Way To Die: Steam Edition,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153207,521570,You Have 10 Seconds 2,4,4,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153208,519140,Minds Eyes,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...

In [6]:
df_items.to_csv('items.csv')

In [5]:
df_items = pd.read_csv('items.csv')

In [7]:
df_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5153209 entries, 0 to 5153208
Data columns (total 8 columns):
 #   Column            Dtype
---  ------            -----
 0   item_id           object
 1   item_name         object
 2   playtime_forever  int64
 3   playtime_2weeks   int64
 4   user_id           object
 5   items_count       int64
 6   steam_id          object
 7   user_url          object
dtypes: int64(3), object(5)
memory usage: 314.5+ MB

In [9]:
#Se observan 59104 duplicados, por lo que se decide borrarlos.

df_items = df_items.drop_duplicates(keep='first')
df_items

,item_id,item_name,playtime_forever,playtime_2weeks,user_id,items_count,steam_id,user_url
0,10,Counter-Strike,6,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,20,Team Fortress Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,30,Day of Defeat,7,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,40,Deathmatch Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
4,50,Half-Life: Opposing Force,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
...,...,...,...,...,...,...,...,...
5153204,346330,BrainBread 2,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153205,373330,All Is Dust,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153206,388490,One Way To Die: Steam Edition,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153207,521570,You Have 10 Seconds 2,4,4,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153208,519140,Minds Eyes,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...

In [2]:
df_items = df_items.drop('playtime_2weeks', axis=1)
df_items.columns

NameError: name 'df_items' is not defined

In [1]:
df_items.to_csv('items.csv', index = False)

NameError: name 'df_items' is not defined